with open('ats_frontend_main/components/company/auth-policy-card.tsx', 'r', encoding='utf-8') as f:
    text = f.read()

text = text.replace('const [savingSection, setSavingSection] = useState<string | null>(null);\n  const saving = savingSection !== null;', 'const [saving, setSaving] = useState(false);')
text = text.replace('onClick={() => handleSave(\'domains\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-primary hover:bg-primary/90">\n                  <Save className="h-3.5 w-3.5 mr-1.5" />\n                  {savingSection === \'domains\' ? "Saving..." : "Save Email Whitelist"}', 'onClick={() => handleSave(\'basic\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-primary hover:bg-primary/90">\n                  <Save className="h-3.5 w-3.5 mr-1.5" />\n                  {saving ? "Saving..." : "Save Email Whitelist"}')

# Now do it properly
text = text.replace('const [saving, setSaving] = useState(false);', 'const [savingSection, setSavingSection] = useState<string | null>(null);\n    const saving = savingSection !== null;')
text = text.replace('setSaving(true);', 'setSavingSection(section);')
text = text.replace('setSaving(false);', 'setSavingSection(null);')
text = text.replace('const handleSave = async () => {', 'const handleSave = async (section: string = \'all\') => {')

text = text.replace('onClick={() => handleSave(\'basic\')}', 'onClick={() => handleSave(\'all\')}')
text = text.replace('onClick={() => handleSave(\'all\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-primary hover:bg-primary/90">\n                  <Save className="h-3.5 w-3.5 mr-1.5" />\n                  {saving ? "Saving..." : "Save Authentication Methods"}', 'onClick={() => handleSave(\'basic\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-primary hover:bg-primary/90">\n                  <Save className="h-3.5 w-3.5 mr-1.5" />\n                  {savingSection === \'basic\' ? "Saving..." : "Save Authentication Methods"}')
text = text.replace('onClick={() => handleSave(\'all\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-primary hover:bg-primary/90">\n                  <Save className="h-3.5 w-3.5 mr-1.5" />\n                  {saving ? "Saving..." : "Save Email Whitelist"}', 'onClick={() => handleSave(\'domains\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-primary hover:bg-primary/90">\n                  <Save className="h-3.5 w-3.5 mr-1.5" />\n                  {savingSection === \'domains\' ? "Saving..." : "Save Email Whitelist"}')
text = text.replace('onClick={() => handleSave(\'all\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-primary hover:bg-primary/90">\n                  <Save className="h-3.5 w-3.5 mr-1.5" />\n                  {saving ? "Saving..." : "Save Tenant ID Lock"}', 'onClick={() => handleSave(\'tenant\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-primary hover:bg-primary/90">\n                  <Save className="h-3.5 w-3.5 mr-1.5" />\n                  {savingSection === \'tenant\' ? "Saving..." : "Save Tenant ID Lock"}')
text = text.replace('onClick={() => handleSave(\'all\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-emerald-600 hover:bg-emerald-700 text-white">\n                  <RefreshCw className={`h-3.5 w-3.5 mr-1.5 ${saving ? "animate-spin" : ""}`} />\n                  {saving ? "Generating..." : "Save App & Generate URLs"}', 'onClick={() => handleSave(\'sso\')} disabled={saving || loading} size="sm" className="text-xs font-bold px-4 cursor-pointer bg-emerald-600 hover:bg-emerald-700 text-white">\n                  <RefreshCw className={`h-3.5 w-3.5 mr-1.5 ${savingSection === \'sso\' ? "animate-spin" : ""}`} />\n                  {savingSection === \'sso\' ? "Generating..." : "Save App & Generate URLs"}')

with open('ats_frontend_main/components/company/auth-policy-card.tsx', 'w', encoding='utf-8') as f:
    f.write(text)
